
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: nihongonotenet-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nihongonote
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: nihongonotenet-web-1
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
